[workspace]
resolver = "2"
members = [
  "seqgen",
  "sequential",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
derive_more = "0.99.17"
either = "1.9.0"
test-case = "3.2.1"
