[package]
name = "sequential"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
either = "1.9.0"

[dev-dependencies]
test-case = "3.2.1"
